
name: CI


on:
 
  push:
    branches: [ "CICDNAVEEN" ]
  pull_request:
    branches: [ "CICDNAVEEN" ]


  workflow_dispatch:


jobs:

  build:
    
    runs-on: ubuntu-latest

   
    steps:
     
      - uses: actions/checkout@v3
      - name: set up JDK 1.8
      - uses: actions/setup-java@v1
      with:
          java-version: 1.8
      - name: Build android application        
        run: ./gradlew build

    
      - name: Run a multi-line script
        run: |
          
